version: '2'

networks:
  testlink-tier:

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - MARIADB_PASSWORD=my_passwd
      - ~/etc/timezone:/etc/localtime:ro
    networks:
      - testlink-tier
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - TESTLINK_DATABASE_USER=bn_testlink
    - TESTLINK_DATABASE_NAME=bitnami_testlink
    - TESTLINK_DATABASE_PASSWORD=my_passwd
    - TESTLINK_EMAIL=mymailaddress@gmail.com
    - MARIADB_HOST=mariadb
    - MARIADB_PORT_NUMBER=3306
    - MARIADB_ROOT_USER=root
    - MARIADB_ROOT_PASSWORD=
    - SMTP_ENABLE=true
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mymailaddress@gmail.com
    - SMTP_PASSWORD=password
    - SMTP_CONNECTION_MODE=tls
    - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_mysql
    - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_testlink
    - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=my_passwd
    - ~/etc/timezone:/etc/localtime:ro
    networks:
      - testlink-tier
    volumes:
      - 'apache_data:/bitnami/apache'
      - 'phpmyadmin_data:/bitnami/php'
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

  phpmyadmin:
    image: bitnami/phpmyadmin
    volumes:
      - 'phpmyadmin_data:/bitnami'
    depends_on:
      - mariadb
    ports: 
      - '8080:80'
    environment:
      - PHPMYADMIN_ALLOW_NO_PASSWORD=true
      - ~/etc/timezone:/etc/localtime:ro
    networks: 
      - testlink-tier 

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
  apache_data:
    driver: local
  phpmyadmin_data:
    driver: local

